[font]
size = 16.0

[keyboard]
bindings = [
	{ key = "F11", action = "ToggleFullscreen" },
	{ key = "N", mods = "Control", action = "SpawnNewInstance" }
]

[window]
opacity = 0.98

padding.x = 10
padding.y = 10

# decorations = "Full"
# decorations_theme_variant = "Light" # "Dark"

