#!/bin/bash
# java 5
function java7 {
  export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_55.jdk/Contents/Home
  export PATH=$JAVA_HOME/bin:$PATH
}
alias cdja='cd ~/src/java'
alias clipme='eclipse >& /dev/null'
