#!/bin/bash
# java 5
function java5 {
  export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/1.5/Home
  export PATH=$JAVA_HOME/bin:$PATH
}
function java7 {
  export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_25.jdk/Contents/Home
  export PATH=$JAVA_HOME/bin:$PATH
}
