#!/usr/bin/env bash
pass_dir=~/jobs/orange/pass.d

for f in $(ls "${pass_dir}"); do
  alias "${f}pass"="cat ${pass_dir}/${f} | tr -d '\n' | pbcopy"
done

# projects  
ipop_dir=~/src/java/orange/ipop
alias envipop="source ${ipop_dir}/env.sh"
alias cdipop="cd ${ipop_dir}/portal/ipop-ui && envipop && java5"
alias cdrbus="cd ${ipop_dir}/rbus/bo && envipop"
