#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:   	     disable-gpe66
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: disable /sys/firmware/acpi/interrupts/gpe66
# Description:  also see init-d-script
### END INIT INFO

# Author: thenrio <thierry.henrio@gmail.com>
#
# tested using
#
#   insserv -n disable-gpe66
#
# activate using
#
#   insserv disable-gpe66
#
# log is really syslog
#
set -e
set -x

DESC="gpe66 disabled"

. /lib/lsb/init-functions
log_action_msg "$DESC ..."

echo 'disable' > /sys/firmware/acpi/interrupts/gpe66


exit 0
