#!/usr/bin/perl
#
# vi: set ft=perl :
#
# see https://aur.archlinux.org/packages/urxvt-fullscreen/
# see http://stackoverflow.com/questions/9783198/how-to-make-rxvt-start-as-fullscreen

sub on_user_command {
  my ($self, $cmd) = @_;
  if ($cmd eq "fullscreen:switch") {
    my $dummy = `wmctrl -r :ACTIVE: -b toggle,fullscreen`;
  }
}

