# see /etc/paths
# append a self bin path
export PATH=$PATH:$HOME/bin

# (eval of dircolors output) has effect on ls program.
# see dircolors/makefile
#
eval "$(dircolors $HOME/.dircolors)"

# langs (python crash)
# http://patrick.arminio.info/blog/2012/02/fix-valueerror-unknown-locale-utf8/
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# exit hook for non interractive session (git clone)
if [ -z "$PS1" ]; then
  # this is added by /etc/paths ... did not grep when it is read :)
  export PATH="$PATH:/usr/local/bin"
  return
fi

set -o vi
# FIXME __dirname__=`dirname $(readlink "$0")`
# http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
# a real mess
#
__dirname__=~/src/dotfiles/bash
# sources
for f in ${__dirname__}/sources.d/* ; do . $f; done
# aliases
for f in ${__dirname__}/aliases.d/* ; do . $f; done

# editor
export EDITOR="nvim"

# rbenv
export PATH="$PATH:$HOME/.rbenv/bin"
eval "$(rbenv init -)"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
