# see /etc/paths
# append a self bin path
export PATH=$PATH:$HOME/bin

# langs ( python crash )
# http://patrick.arminio.info/blog/2012/02/fix-valueerror-unknown-locale-utf8/
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# exit hook for non interractive session (git clone)
if [ -z "$PS1" ]; then
  # this is added by /etc/paths ... did not grep when it is read :)
  export PATH="$PATH:/usr/local/bin"
  return
fi

set -o vi
# FIXME __dirname__=`dirname $(readlink "$0")`
__dirname__=~/src/dotfiles/me/bash
# sources
for f in ${__dirname__}/sources.d/* ; do . $f; done

# aliases
. ${__dirname__}/aliases

# editor
export EDITOR='vim'

# rbenv
export PATH="$PATH:$HOME/.rbenv/bin"
eval "$(rbenv init -)"

# bash completion on osx is broken!
if [  $( command -v brew ) ]  && [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

# vagrant
# export VAGRANT_LOG=INFO

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
